server:
  port: 80

#注册Eureka
eureka:
  client:
    #表示是否将自己注册进eureka server,默认是true
    register-with-eureka: false
    service-url:
      #设置注册地址
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
