server:
  port: 8002

#spring的配置
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 356307
#mybatis的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tb.springcloud.entities

#注册Eureka
eureka:
  client:
    #表示是否将自己注册进eureka server,默认是true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #设置注册地址
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
